### ISSUE TITLE
Add 'this contact issue resolved' tickybox to contacts

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#25]

**Comment by Captainkirkdawson** [comment]
I do not believe we retain contact messages. When addressed they are deletred

**Comment by CommsCoord** [comment]
That is correct, currently they are deleted once addressed, either by myself or the CC/SC.  Currently there is no facility to retain the original message and any response on our part, as it is all done via email, which was set up by the coordinator. Which is the reason I would like everything to come through Comms, so a record can be maintained until these functions can be set up on FR. We currently see what comes in but every coord does not always copy us into the response, or lets us know the contact has been completed. Too many open ends currently and no streamlined methodology for a 'paper trail' to be left.

**Comment by edickens** [comment]
I'm not sure if it will work, but the key, as I see it, to Comms getting 
a copy is for the "Reply", instead of "Reply All", to get a copy.  If 
the version sent to Comms is part of "To:" instead of "cc:", then 
perhaps "Reply" will create a copy to all those to whom it is addressed 
and that would include Comms.
E

**Comment by PatReynolds** [comment]
Pat to create .freegenealogy.org.uk  account for Sandra

**Comment by PatReynolds** [comment]
Done 5/1/2017
